app/views/media_objects/_metadata_display.html.erb
https://issues.umd.edu/browse/LIBBCM-31
=> LIBBCM-31. Remove "View Raw Metadata" and "View Fedora Objects".

app/controllers/catalog_controller.rb
https://issues.umd.edu/browse/LIBBCM-28
=> LIBBCM-28. Remove Browse/Limit fields.

app/views/catalog/_home_text.html.erb, spec/features/capybara_homepage_spec.rb, spec/features/secure_routes_spec.rb
https://issues.umd.edu/browse/LIBBCM-27
=> LIBBCM-27. Remove featured content from the home page.

Gemfile, Gemfile.lock
https://issues.umd.edu/browse/LIBBCM-43
=> LIBBCM-43. Removed pg gem version.

config/initializers/media_object_controller.rb
Remove the Share link from the content detail page
https://issues.umd.edu/browse/LIBBCM-26
=> LIBBCM-26. Remove the Share link.

app/assets/stylesheets/avalon.scss, app/controllers/media_objects_controller.rb, app/helpers/media_objects_helper.rb, app/views/media_objects/_download.html.erb, app/views/media_objects/_item_view.html.erb, config/avalon.yml.example, config/routes.rb
https://issues.umd.edu/browse/LIBBCM-30
=> LIBBCM-30. Add file download

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/controllers/catalog_controller.rb, app/controllers/search_history_controller.rb, app/models/media_object.rb, app/models/search_builder.rb, config/routes.rb
https://issues.umd.edu/browse/LIBBCM-29
=> LIBBCM-29. Add new discovery options for date and time.

config/settings.yml, env.dist
https://issues.umd.edu/browse/LIBBCM-47
=> LIBBCM-47. Move host specific configuration to env file.

.gitignore, README.md, config/controlled_vocabulary.yml, docker-compose.yml
https://issues.umd.edu/browse/LIBAVALON-64
=> LIBAVALON-64. Setup Avalon Pilot development environment

script/locking_runner
https://issues.umd.edu/browse/LIBBCM-122
=> LIBBCM-122. Update locking_runner script to delete stale lock files

README.md
https://issues.umd.edu/browse/LIBAVALON-61
=>  LIBAVALON-61. Create Units for Avalon Pilot.

app/assets/javascripts/media_player_wrapper/avalon_player_new.es6, app/models/concerns/master_file_behavior.rb
https://issues.umd.edu/browse/LIBBCM-125
=> LIBBCM-125. Fix audio playback on mejs with AWS CloudFront.

app/controllers/admin/users_controller.rb, app/models/ability.rb, app/views/_user_util_links.html.erb, app/views/admin/users/index.html.erb, config/locales/en.yml, config/routes.rb
https://issues.umd.edu/browse/LIBAVALON-79
=> LIBAVALON-79. Display users list.

app/controllers/admin/users_controller.rb, app/controllers/application_controller.rb, app/models/ability.rb, app/views/admin/users/index.html.erb, app/views/modules/_user_management.html.erb, config/routes.rb
https://issues.umd.edu/browse/LIBAVALON-78
=> LIBAVALON-78. Login as user feature.

config/initializers/mailer.rb
https://issues.umd.edu/browse/LIBBCM-130
=> LIBBCM-130. Enable configuring aws_sdk mailer from environment variable.

lib/tasks/avalon.rake
https://issues.umd.edu/browse/LIBBCM-126
=> LIBBCM-126. Migrate development instance to AWS

app/models/master_file.rb, lib/avalon/batch/entry.rb
https://issues.umd.edu/browse/LIBBCM-104
=> LIBBCM-104. Store additional files with master file.

app/models/master_file.rb, lib/avalon/batch/entry.rb
https://issues.umd.edu/browse/LIBBCM-104
=> LIBBCM-104. Store JSON NLP output from IBM Watson NLU.

lib/avalon/batch/ingest.rb
https://issues.umd.edu/browse/LIBBCM-126
=> LIBBCM-126. Fix SQS batch load error.

app/models/concerns/master_file_behavior.rb, config/settings.yml
https://issues.umd.edu/browse/LIBBCM-139
=> LIBBCM-139. Ensure correct audio playback quality is selected

app/helpers/security_helper.rb, config/initializers/devise.rb
Also, set default devise reply-to email.
https://issues.umd.edu/browse/LIBBCM-126
=> LIBBCM-126. Removed RTMP streaming support.

app/services/solr_collection_admin.rb
https://issues.umd.edu/browse/LIBBCM-140
=> LIBBCM-140. Output the backup name on console.

lib/tasks/avalon.rake
- Generates derivatives for Masterfiles that do not have derivaatives attached to them.
https://issues.umd.edu/browse/LIBBCM-145
=> LIBBCM-145. Added rake task to create derivatives.

.dockerignore, Gemfile, README.md, UMD-README.md
https://issues.umd.edu/browse/LIBAVALON-83
=> LIBAVALON-83. Install latest Avalon 7.x version to k8s test cluster

Gemfile, Gemfile.lock, app/controllers/samvera/persona/users_controller.rb, app/models/user.rb, config/initializers/devise.rb, config/routes.rb, lib/avalon/authentication.rb
https://issues.umd.edu/browse/LIBAVALON-88
=> LIBAVALON-88. Added Omniauth SAML auth provider.

app/models/user.rb, config/initializers/devise.rb
- Allow parsing multiple values in SAML response.
- Update Avalon groups based on SAML groups.
https://issues.umd.edu/browse/LIBAVALON-89
=> LIBAVALON-89. Setup Grouper based authorization.

app/models/concerns/permalink.rb, app/models/media_object.rb
https://issues.umd.edu/browse/LIBAVALON-91
=> LIBAVALON-91. Integrate with handle service.

app/assets/stylesheets/avalon.scss, app/views/media_objects/_aeon_request_form.html.erb, app/views/media_objects/_item_view.html.erb
https://issues.umd.edu/browse/LIBAVALON-93
=> LIBAVALON-93. Add Aeon "Request from Special Collections" link.

app/assets/javascripts/select.js.coffee, app/assets/stylesheets/avalon.scss, app/helpers/application_helper.rb, app/views/_user_util_links.html.erb, app/views/catalog/_document_list.html.erb, app/views/catalog/_facet_group.html.erb, app/views/catalog/_search_results.html.erb, app/views/catalog/_select_all.html.erb, app/views/catalog/_thumbnail_media_object.html.erb, app/views/catalog/index.html.erb, app/views/layouts/avalon.html.erb, app/views/modules/_avalon_search_form.html.erb, app/views/modules/_global_navigation.html.erb, app/views/shared/_ajax_modal.html.erb, config/locales/blacklight.en.yml
https://issues.umd.edu/browse/LIBAVALON-108
=> LIBAVALON-108. Fix accessibility issues.

app/assets/stylesheets/avalon.scss, app/views/layouts/avalon.html.erb, app/views/modules/_footer.html.erb
https://issues.umd.edu/browse/LIBAVALON-126
=> LIBAVALON-126. Implement the footer from digital.lib.

app/views/layouts/avalon.html.erb
https://issues.umd.edu/browse/LIBAVALON-109
=> LIBAVALON-109. Add Google Tag Manager script.

app/assets/stylesheets/custom.css, app/javascript/components/collections/list/CollectionListStickyUtils.js, app/views/layouts/avalon.html.erb
https://issues.umd.edu/browse/LIBAVALON-108
=> LIBAVALON-108. More accessibility fixes.

app/assets/stylesheets/custom.css
https://issues.umd.edu/browse/LIBAVALON-134
=> LIBAVALON-134. Fix item focus issue.

app/assets/stylesheets/custom.css, app/views/catalog/index.html.erb
https://issues.umd.edu/browse/LIBAVALON-122
=> LIBAVALON-122. Featured collection / carousel theming.

app/models/concerns/permalink.rb, app/models/media_object.rb, config/initializers/generate_permalink.rb
Reverted the previous changes.
https://issues.umd.edu/browse/LIBAVALON-91
=> LIBAVALON-91. Moved the handle integration code to initializer.

app/views/_user_util_links.html.erb, app/views/modules/_global_navigation.html.erb, app/views/modules/_header.html.erb
Also, update the digital collections link.
https://issues.umd.edu/browse/LIBAVALON-140
=> LIBAVALON-140. Added Home link to top menu.

app/models/ability.rb
https://issues.umd.edu/browse/LIBAVALON-153
=> LIBAVALON-153. Grant collection Editors ability to edit published items.

app/controllers/users/omniauth_callbacks_controller.rb, app/controllers/users/sessions_controller.rb, config/settings.yml
https://issues.umd.edu/browse/LIBAVALON-150
=> LIBAVALON-150. Fix login with redirect url bug.

config/settings.yml, docker-compose.yml, lib/avalon/authentication.rb
https://issues.umd.edu/browse/LIBAVALON-150
=> LIBAVALON-150. Set the assertion_consumer_service_url config.

app/models/ability.rb
https://issues.umd.edu/browse/LIBAVALON-142
=> LIBAVALON-142. Mix MasterFile section update failure.

app/controllers/application_controller.rb
https://issues.umd.edu/browse/LIBAVALON-163
=> LIBAVALON-163. Update IP Access Control IP source.

config/controlled_vocabulary.yml.example, config/initializers/generate_permalink.rb
https://issues.umd.edu/browse/LIBAVALON-164
=> LIBAVALON-164. Update handle if handle identifier provided.

app/assets/stylesheets/custom.css
https://issues.umd.edu/browse/LIBAVALON-157
=> LIBAVALON-157. Increased contrast of the remove button.

app/assets/stylesheets/custom.css
https://issues.umd.edu/browse/LIBAVALON-177
=> LIBAVALON-177. Changed restricted item message link color.

Jenkinsfile
https://issues.umd.edu/browse/LIBAVALON-176
=> LIBAVALON-176. Added Jenkinsfile for CI

app/views/media_objects/_item_view.html.erb
https://issues.umd.edu/browse/LIBAVALON-180
=> LIBAVALON-180. Share button should be displayed for restricted items.

app/models/access_token.rb, db/migrate/20220216184500_create_access_tokens.rb, db/schema.rb, spec/models/access_token_spec.rb
https://issues.umd.edu/browse/LIBAVALON-202
=> LIBAVALON-202. Created AccessToken model.

config/controlled_vocabulary.yml.example
Added "fedora2" and "filename" identifier types.
https://issues.umd.edu/browse/LIBAVALON-241
=> LIBAVALON-241. Added additional "identifier_types"

app/views/modules/_footer.html.erb
- Contact Us - https://libumd.wufoo.com/forms/digitalfeedback/
- Privacy Policy - https://www.lib.umd.edu/about/policies/privacy
https://issues.umd.edu/browse/LIBAVALON-265
=> LIBAVALON-265. Updated links in Avalon footer.

UMD-README.md, umd_docs/AvalonPermissions.md
Document was derived from https://confluence.umd.edu/pages/viewpage.action?pageId=635241505
Added pointer to document in UMD-README.md
https://issues.umd.edu/browse/LIBAVALON-276
=> LIBAVALON-276. Added "AccessPermissions" document

Jenkinsfile
Modified Jenkinsfile so tests would run more smoothly
and clean up after themselves.
Changes include:
* Using the "throttle-concurrents" plugin to limit the
Avalon builds to one build at a time. This replaces the
use of "lockable resource".
* Changing ownership of all files at end of run to the
"ci" user, so Jenkins can clean up the workspace directory.
* Modified RSpec to use the "documentation" formatter, so
test progress can be more easily viewed in the console log.
* Docker volumes are pruned after the test run. Having
Docker volumes from the previous runs was the cause of
ever-increasing test run times.
* Removed "docker_init.sh" script call, because running it
did not appear to be necessary.
https://issues.umd.edu/browse/LIBAVALON-268
=> LIBAVALON-268. Renable tests in Jenkinsfile

app/models/ability.rb
https://issues.umd.edu/browse/LIBAVALON-284
=> LIBAVALON-284. Allow editors to update access control of published items.

app/models/master_file.rb, app/services/master_file_builder.rb
https://issues.umd.edu/browse/LIBAVALON-286
=> LIBAVALON-286. Implement downloads for Google Drive files.

app/views/_user_util_links.html.erb, app/views/access_tokens/_form.html.erb, app/views/access_tokens/index.html.erb, app/views/access_tokens/show.html.erb, app/views/bookmarks/update_access_control.html.erb, app/views/kaminari/_first_page.html.erb, app/views/kaminari/_last_page.html.erb, app/views/kaminari/_next_page.html.erb, app/views/kaminari/_page.html.erb, app/views/kaminari/_prev_page.html.erb, app/views/media_objects/_aeon_request_form.html.erb, app/views/media_objects/_download.html.erb
- Fix menu hover background color.
- Fix button styling for customized views.
https://issues.umd.edu/browse/LIBAVALON-288
https://issues.umd.edu/browse/LIBAVALON-289
=> LIBAVALON-288. LIBAVALON-289. UI Fixes.

app/assets/stylesheets/custom.css
- LIBAVALON-290. Selected Items page buttons styling.
- LIBAVALON-291. Fix dropbox upload modal display.
https://umd-dit.atlassian.net/browse/LIBAVALON-290
https://umd-dit.atlassian.net/browse/LIBAVALON-291
=> LIBAVALON-290, LIBAVALON-291. UI Fixes.

app/jobs/master_file_management_jobs.rb, app/services/master_file_builder.rb
https://umd-dit.atlassian.net/browse/LIBAVALON-293
=> LIBAVALON-293. Fix duplicate file error on uploads.

app/assets/javascripts/application.js, app/assets/javascripts/blacklight/bookmark_toggle.js, app/assets/javascripts/bootstrap-tooltip-noconflict.js, app/assets/javascripts/select_all.js.coffee, app/controllers/bookmarks_controller.rb, app/helpers/application_helper.rb, app/views/catalog/_select_all.html.erb, config/application.rb, config/puma.rb, spec/controllers/bookmarks_controller_spec.rb
- Prevent unnecessary duplicate calls to fcrepo backend.
- Add puma thread configuration.
- Implement limit to number of selected items. 
https://umd-dit.atlassian.net/browse/LIBAVALON-334
=> LIBAVALON-334. Avalon selected items page improvements.

app/views/_user_util_links.html.erb
https://umd-dit.atlassian.net/browse/LIBAVALON-339
=> LIBAVALON-339. Add a "Help" link to the top navigation bar.
