- app/controllers/catalog_controller.rb
- A javascript function is used to determine the width of the facet count and it does not work correctly if all the facets are collapsed.
https://issues.umd.edu/browse/LIBBCM-40
> LIBBCM-40. Configure collapse false for year facet.

- app/assets/stylesheets/avalon.scss
- app/assets/stylesheets/umd_lib_environment_banner.scss
- app/helpers/umd_lib_environment_banner_helper.rb
- app/views/modules/_header.html.erb
- config/initializers/00-inflections.rb
Had to rename the inflections.rb initializer to 00-inflections.rb, so that is is guarenteed to be loaded before any of the other initializers. Otherwise, the Rails autoloading code is unable to find the UMDLibEnvironmentBannerHelper module.
https://issues.umd.edu/browse/LIBBCM-41
> LIBBCM-41. Added environment banners.

- Gemfile
- Gemfile.lock
Versions of roo > 2.6.0 use the first line of a CSV file to determine how many columns are in the file. This was causing Avalon to only get the first two columns of the batch metadata files, and thus considering all batches as having missing metadata.
https://issues.umd.edu/browse/LIBBCM-52
> LIBBCM-52. Pin roo version to 2.6.0.

- app/controllers/media_objects_controller.rb
Removed "download_section" method from "load_and_authorize_resource"
method, as CanCanCan uses the method name for determining which
permission to authorize against (i.e., "download_section", instead of
"read). The "read" permission is manually checked in the
"download_section" method.
Added "download_section" method to "load_resource" action so that the
resource will be loaded (based on id in the URL).
https://issues.umd.edu/browse/LIBBCM-54
> LIBBCM-54. Enable non-admin logged-in users to download files

- config/environments/production.rb
Must specify "harmony: true" when using ES6 syntax.
See https://github.com/lautis/uglifier#es6--es2015--harmony-mode
https://issues.umd.edu/browse/LIBBCM-62
> LIBBCM-62. Specify harmony mode for uglifier.

- app/controllers/auth_forms_controller.rb
- config/initializers/devise.rb
Currently omniauth-identity will just log in a user if the user account
already exists. This adds a failure message and redirects the user back
to the form.
https://issues.umd.edu/browse/LIBBCM-120
> LIBBCM-120 Display user exists message on duplicate registration

- app/services/solr_collection_admin.rb
To be able to restore a collection from backup requires that name does not already exist.
https://issues.umd.edu/browse/LIBBCM-140
> LIBBCM-140. Add option to delete solr collection.

- app/models/user.rb
When there is no Grouper group associated with an user, the login attempt was failing with NPE.
https://issues.umd.edu/browse/LIBAVALON-89
> LIBAVALON-89. Fix login error.

- app/models/master_file.rb
- app/services/master_file_builder.rb
Uploaded files are stored in tmp directory by default, and they are not moved to persistent storage location when the working_file_path is not set. The 'working_file_path' option is not enabled in UMD Avalon to retain the masterfiles from batch uploads in the dropbox directory.
Move uploaded files from /tmp to the 'upload/<DATE>' directory within the collection dropbox directory.
https://issues.umd.edu/browse/LIBAVALON-128
> LIBAVALON-128. Move files to collection dir.

- app/views/layouts/avalon.html.erb
https://issues.umd.edu/browse/LIBAVALON-109
> LIBAVALON-109. Fixed hardcoded gtag id.

- Dockerfile
The current ffmpeg version 4.4 is causing transcoding errors for some of the videos.
https://issues.umd.edu/browse/LIBAVALON-144
> LIBAVALON-144. Use ffmpeg 4.2.2.

- app/services/master_file_builder.rb
As a sideeffect of LIBAVALON-128, bitstream uploads from dropbox were erroring out.
https://issues.umd.edu/browse/LIBAVALON-151
> LIBAVALON-151. Fix dropbox upload error.

- UMD-README.md
- docker-compose.yml
Modified the configuration, restoring the Avalon Rails application to
run on port 3000, instead of port 3001. It is believed that the configuration change to run on port 3001 was
inadvertent (caused by a port conflict when working with the
"umd-handle" Rails application).
The Avalon "README.md" indicates that the system should be started using
`docker-compose up avalon worker` which only runs the containers
necessary for Avalon (skipping the test containers). Modified the
"UMD-README.md" to use this command, to avoid the spurious
warnings/errors in the log
Added "DIGITAL_COLLECTIONS_URL" to the Avalon environment, as it is
used by the HTML templates. Without this environment variable, accessing the "Manage | Manage Users"
link in Avalon displays an error. …
> LIBAVALON-173. Improve local development environment setup

- app/views/catalog/_facet_pagination.html.erb
Fixes extraneous "</span>" tags showing in the pagination section
of modal dialogs. This is a core Avalon issue, coming from the
"blacklight" gem.
This file was taken from an upstream Avalon fix that will be included in
Avalon v7.3 (see https://github.com/avalonmediasystem/avalon/pull/4335).
https://issues.umd.edu/browse/LIBAVALON-156
> LIBAVALON-156. Fix "span" tag in pagination section of modal dialogs

- app/assets/stylesheets/custom.css
- app/controllers/master_files_controller.rb
- app/controllers/media_objects_controller.rb
- app/controllers/supplemental_files_controller.rb
- app/models/ability.rb
- app/models/media_object.rb
- app/views/media_objects/_item_view.html.erb
- Add "public" discover group to all MediaObjects in Solr index.
- Show metadata for restricted items.
- Media playback and supplemental file access still remains restricted.
https://issues.umd.edu/browse/LIBAVALON-168
> LIBAVALON-168. Change restricted content behavior.

- app/models/master_file.rb
- config/settings.yml
- spec/models/master_file_spec.rb
Modified the "config/settings.yml" file to move master file binaries (access copies) from the dropbox directory, to an "archive" directory as part of the upload process.
The "archive" directory is configured to be the "/masterfile/archive" directory, which makes it a sibling to the "dropbox" directory.
Added a "post_processing_move_relative_filepath" method to "app/models/master_file.rb" which generates a relative filepath built from the media object id, using the "Noid::Rails.treeify" method. This is the same method used to "mint" Fedora identifiers (see "ActiveFedora::Base.translate_id_to_uri" in "config/initializers/active_fedora_general.rb"
Modified the "manage_master_file" method to use the "post_processing_move_relative_filepath" method when naming files.
Added RSpec tests for the …
> LIBAVALON-196. Protect the access copy by removing from the dropbox after ingest

- app/controllers/master_files_controller.rb
- app/controllers/media_objects_controller.rb
- app/models/ability.rb
- app/views/media_objects/_metadata_display.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/master_files_controller_spec.rb
- spec/controllers/media_objects_controller_spec.rb
- spec/models/ability_spec.rb
Added "master_file_download" permission to "ability.rb", which allows
a master file (i.e., "access copy") to be downloaded if the user is
a member of the collection the media_object associated with the master
file is part of. Due to the way permissions are setup, "admin" users
bypass this permission check entirely.
Updated "app/controllers/media_objects_controller.rb" to determine if
master file downloads are allowed. In the case of multiple master files,
all master files must be downloadable (this is not expected to be an
issue in practice, as all the files should be part of the same
collection).
Added a "Downloads" section to
"app/views/media_objects/_metadata_display.html.erb" that presents a
download link for each master file, if permitted.
Added "download" endpoint to the …
> LIBAVALON-197. Add option to download the access copy

- app/controllers/application_controller.rb
- app/controllers/media_objects_controller.rb
- app/models/ability.rb
- app/models/access_token.rb
- app/views/media_objects/_metadata_display.html.erb
- spec/controllers/application_controller_spec.rb
- spec/controllers/media_objects_controller_spec.rb
- spec/factories/access_token.rb
- spec/models/ability_spec.rb
- spec/models/access_token_spec.rb
Added an "active?" flag to "app/models/access_token.rb" AccessToken to easily determine that the token has not expired and not been revoked.
Added handling for an "access_token" request param to the "current_ability" method of "app/controllers/application_controller.rb", so that the parameter gets added as a session option to the current Ability instance.
In "app/models/ability.rb":
* Added an "access_token_download_group_name" method to generate the “allow_download_[MEDIA_OBJECT_ID]” user group from a given media object id
* Added an "access_token_user_groups" method, called from the "user_groups" method, to append the an access token download group, if an active token is provided that allows downloads.
* Created an "is_master_file_download_allowed?" method that handles all the logic for …
> LIBAVALON-206. Added token based access to master file downloads

- app/controllers/application_controller.rb
- app/controllers/media_objects_controller.rb
- app/models/ability.rb
- app/models/access_token.rb
- app/views/media_objects/_metadata_display.html.erb
- spec/controllers/application_controller_spec.rb
- spec/controllers/media_objects_controller_spec.rb
- spec/factories/access_token.rb
- spec/models/ability_spec.rb
- spec/models/access_token_spec.rb
Add token based access control to stream a media file that a user would otherwise not be able to access.
Added "allow_streaming_of?" methods to AccessToken to determine if streaming is allowed for a particular token and media object.
In "app/models/ability.rb" added "can stream?" and "is_streaming_allowed?" methods to control whether streaming is allowed. Kept existing behavior to allow streaming if "can? full_read" is permitted, and added additional override to permit streaming if "AccessToken.allow_streaming_of?" returns true.
Modified "app/controllers/media_objects_controller.rb" to use the new streaming ability.
In "spec/models/ability_spec.rb", moved "#user_groups", and "masterfile_download Ability" tests underneath the overarching "Ability" description, so that the RSpec …
> LIBAVALON-207. Add can_stream permission

- app/assets/stylesheets/avalon/_buttons.scss
- app/views/media_objects/_download.html.erb
- app/views/media_objects/_item_view.html.erb
Added a "Download" button next to the "Share" button on the media object
detail page.
Note: The "Download" button is placed to the left of the "Share" button,
(not to the right, as suggested in the issue description), because
left-clicking the "Share" button displays a tabbed panel. If the
"Download" button were placed to the right, the "Download" button
would be displaced to underneath the opened panel. It was not
immediately obvious how to correct this, so simply moved the
"Download" button to the left of the "Share" button.
Left-clicking "Download" button opens up a modal dialog, which shows a
bulleted list of the available downloads. This is to handle the
(potential) case of a media object have multiple master files to
download, and is similar in appearance to the "Downloads" panel in …
> LIBAVALON-213. Added a Download button to the media object detail page

- app/controllers/access_tokens_controller.rb
- app/controllers/media_objects_controller.rb
- app/models/access_token.rb
- app/views/access_tokens/_form.html.erb
- app/views/access_tokens/show.html.erb
- app/views/modules/_access_control.html.erb
- config/locales/en.yml
- spec/controllers/access_tokens_controller_spec.rb
- spec/controllers/media_objects_controller_spec.rb
- spec/models/access_token_spec.rb
Implemented the following functionality:
* On the "Edit Media Object > Access Control" page, added an "Access Token" panel that displays a table of all active tokens, and a "Create a new token" button.
* On the create access tokens ("new") page:
* Modified the "Save" button to redirect on successful access token creation to the access token detail ("show") page, instead of going back to the access tokens list ("index") page.
* Modified the "Cancel" button to return to the "Edit Media Object > Access Control" page, when the "Media object ID" field is populated by default (i.e., not entered by the user). Otherwise the "Cancel" button returns to the access tokens list ("index") page.
* On the access token detail ("show") page:
* Added two additional buttons, "Access Tokens List", which …
> LIBAVALON-205. UI for creating new AccessTokens for a MediaObject

- Jenkinsfile
The Avalon tests are taking an extremely long time to run in Jenkins,
and usually have many (spurious) failures. Continuing to run the tests
is causing resource issues on Jenkins, so disabling the tests until
Jenkins can run the test consistently.
https://issues.umd.edu/browse/LIBAVALON-221
> LIBAVALON-221. Disabled testing in Jenkinsfile

- app/controllers/access_tokens_controller.rb
- app/models/ability.rb
- app/models/access_token.rb
- spec/controllers/access_tokens_controller_spec.rb
- spec/controllers/application_controller_spec.rb
- spec/controllers/media_objects_controller_spec.rb
- spec/factories/access_token.rb
- spec/factories/collections.rb
- spec/jobs/cleanup_access_token_job_spec.rb
- spec/models/ability_spec.rb
- spec/models/access_token_spec.rb
This pull request replaces Pull Request #99
* Must be an admin or  collection member (manager, editor, depositor) to create or update its access tokens for a media object.
* If a user doesn't have permission to create or update an access token, return a "media object not found" error to prevent leaking information about which media objects do exist
* Added a list_all AccessToken ability for administrators; collection members can only see tokens for objects in collections they have access to
https://issues.umd.edu/browse/LIBAVALON-216
> LIBAVALON-216. Authorization rules for AccessTokens

- app/controllers/access_tokens_controller.rb
- app/models/ability.rb
- app/views/_user_util_links.html.erb
- app/views/access_tokens/index.html.erb
- spec/controllers/access_tokens_controller_spec.rb
- spec/features/capybara_navigation_spec.rb
Two related changes were implemented as part of this issue:
Added "Manage Access Tokens" entry in the "Manage" dropdown on the navigation bar. Placed the entry first, so that the items in the dropdown would be in alphabetical order.
Added an AccessToken "manage" ability to "models/ability.rb", and restricted display of the "Manage Access Tokens" entry to users that have the AccessToken "manage" ability, which should be administrators (which can "manage" anything), or users that are managers, editors, or depositors of any collection.
Also, added an "Access Tokens" header to the access tokens "index" page, to be consistent with other Avalon pages.
While working on this issue it was noticed that access token endpoints are accessible (via a direct URL) to any authenticated user. This includes …
> LIBAVALON-226. Create button that directly takes user to access token list

- Gemfile
- Gemfile.lock
- app/models/lease.rb
- app/services/umd_ip_manager.rb
- spec/models/lease_spec.rb
- spec/services/umd_ip_manager_spec.rb
UmdIPManager service class can be used to get the list of all groups, the list of groups that contain a particular IP address, or whether a particular IP address is contained by a particular group.
https://issues.umd.edu/browse/LIBAVALON-263
> LIBAVALON-263. Implemented UmdIPManager service.

- app/controllers/admin/collections_controller.rb
- app/controllers/media_objects_controller.rb
- app/helpers/application_helper.rb
- app/jobs/bulk_action_jobs.rb
- app/models/ability.rb
- app/models/access_control_step.rb
- app/models/admin/collection.rb
- app/models/concerns/virtual_groups.rb
- app/models/media_object.rb
- app/services/umd_ip_manager.rb
- app/views/modules/_access_control.html.erb
- app/views/modules/_access_object.html.erb
- config/locales/en.yml
- spec/controllers/admin_collections_controller_spec.rb
- spec/controllers/media_objects_controller_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/models/concerns/virtual_groups_spec.rb
- spec/models/media_object_spec.rb
- spec/rails_helper.rb
- spec/services/mock_umd_ip_manager.rb
- spec/services/umd_ip_manager_spec.rb
This work is based on the changes in [LIBAVALON-263](https://issues.umd.edu/browse/LIBAVALON-263).
* In the UmdIPManager class, the term "base_key" is potentially confusing, so changed it to simply "key" to match the data coming from IP Manager. The original intention was to distinguish between the "base_key" (from IP Manager) and the "prefixed_key" used in Avalon, but "key" is simpler, the distinction remains.
* Added default mock for UmdIPManager functionality. Because of the way the UmdIPManager functionality will be integrated into Avalon, calls to the IP Manager may occur in tests that are not directly related to UmdIPManager. To minimize the burden, modified the "spec/rails_helper.rb" class so that, by default, mock UmdIPManager functionality (via the "enable_umd_ip_manager_mock" …
> LIBAVALON-264. Add form to select and add an IP Manager group to an item's special access

- app/models/ability.rb
- spec/controllers/media_objects_controller_spec.rb
- spec/models/ability_spec.rb
Also fixed the test for access tokens to not log in with the manager user.
https://issues.umd.edu/browse/LIBAVALON-238
> LIBAVALON-238. Only honor access tokens for published objects.

- app/javascript/components/CollectionList.js
- app/views/collections/index.html.erb
- Added a "sort" parameter to the CollectionList constructor; retains stock Avalon behavior of defaulting to "unit" if no "sort" parameter is given
- Set the "sort" parameter to "az" on the collections index page
https://issues.umd.edu/browse/LIBAVALON-278
> LIBAVALON-278. Sort collections A-Z on the /collections page.

- UMD-README.md
- app/views/layouts/avalon.html.erb
- app/views/layouts/embed.html.erb
- app/views/modules/_matomo_analytics.html.erb
- env_template
- spec/views/matomo_analytics_spec.rb
1) Removed the “Google Analytics” script added by UMD to the “app/views/layouts/avalon.html.erb” file in LIBAVALON-109
2) Added three environment variables to the "env_template" file to control the settings in the Matomo Analytics JavaScript script:
* MATOMO_ANALYTICS_URL - URL of the UMD Matomo website
* MATOMO_ANALYTICS_SITE_ID - The Matomo-provided site id
* MATOMO_ANALYTICS_CDN_SRC = CDN URL to the UMD Matomo JavaScript script
Intentionally left the "MATOMO_ANALYTICS_SITE_ID" environment variable empty to prevent Matomo tracking in local development.
3) Added a "matomo_analytics" view partial in "app/views/modules/_matomo_analytics.html.erb" containing the Matomo Analytics JavaScript from the Matomo website, modified to use the environment variables. In the partial, the script is not …
> LIBAVALON-312. Replaced Google Analytics with Matomo Analytics

- UMD-README.md
Updated the "Development Setup" instructions with the additional steps needed to run Avalon on an M-series (Apple Silicon) MacBook.
https://umd-dit.atlassian.net/browse/LIBAVALON-287
> LIBAVALON-287. Updated UMD-README.md for M-series MacBooks

- UMD-README.md
Updating the README to note that the host name should be host.docker.internal when Avalon is being run in docker and the Handle Service isn't.
https://umd-dit.atlassian.net/browse/LIBAVALON-316
> LIBAVALON-316: Updating known issues to mention change of umd handle url

- app/views/media_objects/_multipart_dropdown_field.html.erb
The hidden inputs no longer seems to be used, and it is removed in Avalon 7.6. The hidden inputs were causing the form to include previous state in addition to the updated values.
https://umd-dit.atlassian.net/browse/LIBAVALON-330
> LIBAVALON-330. Disable hidden fields in multipart dropdown.

- app/controllers/supplemental_files_controller.rb
Copied fix from upstream Avalon: https://github.com/avalonmediasystem/avalon/commit/548d9240e144f54f8c6ba92b12854b2ad57598cf
https://umd-dit.atlassian.net/browse/LIBAVALON-342
> LIBAVALON-342. Allow manager or editor to add a transcript file.

- app/views/modules/_footer.html.erb
The missing footer container div was cuasing the footer to overlap with the timeline divs. Fixed it by adding the footer container div.
https://umd-dit.atlassian.net/browse/LIBAVALON-333
> LIBAVALON-333. Fix timeline index page.

- app/assets/javascripts/avalon_playlists/playlists.js.coffee
- app/assets/javascripts/avalon_timelines/timelines.js.coffee
- app/assets/javascripts/supplemental_files.js
- app/views/media_objects/_file_upload.html.erb
- app/views/playlists/refresh_info.js.erb
With Rails 6, the ajax event handler signature changed to only include "event" arg. All the other args are included in the event.detail property.
Reference: https://guides.rubyonrails.org/v6.1.0/working_with_javascript_in_rails.html#rails-ujs-event-handlers
https://umd-dit.atlassian.net/browse/LIBAVALON-332
> LIBAVALON-332. Fix ujs event handlers

- Gemfile
- Gemfile.lock
Added the "ruby-saml" version to the "Gemfile" and pinned to 1.12.3 (or later 1.12.x) version to mitigate CVE-2024-45409 (see https://github.com/advisories/GHSA-jw9c-mfg7-9rx2).
Without this pinning of the "ruby-saml" gem to 1.12.3, the "omniauth-saml" gem will cause ruby-saml v1.14.0 to be used, which contains the vulnerability.
It is currently not possible to update the "omniauth-saml" gem version to the patched v2.2.1, because it requires Ruby 3.1 or greater.
This customization can likely be removed when upgrading to a later ArchivesSpace version (as long as the "ruby-saml" gem matches a version containing the fix).
https://umd-dit.atlassian.net/browse/LIBAVALON-353
> LIBAVALON-353. ruby-saml - Mitigate CVE-2024-45409

- app/views/master_files/_authenticate.html.erb
Updates the links to the SAML paths, and removes the popup window that would appear when clicking the Sign In button on the page
https://umd-dit.atlassian.net/browse/LIBAVALON-378
> LIBAVALON-378: Adjust Links for Authenticate on Embed Page
